ActionCable
ekifel/TH_QnA pull request #11
Opened 2020-09-20 08:22 UTC by ekifel

2020-09-20 11:03 UTC, IvanShamatov requested changes

2020-09-20 11:03 UTC, IvanShamatov commented on app/models/comment.rb
> +class Comment < ApplicationRecord
Не понимаю, почему этот код впервые появляется здесь, он уже должен был быть в репозитории. Мне кажется, кто-то после мерджа не стащил мастер. Пожалуйста, избавься от кода, который не относится к решению задачи

2020-09-21 15:38 UTC, ekifel commented on app/controllers/application_controller.rb
> +  before_action :get_gon_current_user
Точно. Исправил.

2020-09-21 15:38 UTC, ekifel commented on app/controllers/application_controller.rb
> +    gon.current_user = current_user
Ох, спасибо, на будущее учту)
Исправил

2020-09-21 15:38 UTC, ekifel commented on app/javascript/channels/answers_channel.js
> +            if (gon.current_user != null && gon.current_user.id == data['answer']['user_id']) {
В данном случае оставил похожую проверку, так как она потом все равно используется при рендере клиентского шаблона. В остальных - убрал.

2020-09-21 15:38 UTC, ekifel commented on app/javascript/channels/comments_channel.js
> +                $('#question-'+ gon.question_id +' .comments').prepend("<p>"+ data['body'] + "</p>")
Перенес всю верстку в клиентский шаблонизатор

2020-09-21 15:38 UTC, ekifel commented on app/controllers/answers_controller.rb
> +            template: render_to_string(partial: 'answers/answer', locals: { resource: answer, current_user: nil })
Переделал
Единственное что, не стал в клиентском шаблоне прописывать форму для добавления комментария к ответу, так как не знал что делать с authentication_token, который в форме содержится

2020-09-21 15:38 UTC, ekifel commented on app/models/comment.rb
> +class Comment < ApplicationRecord
Модели комментариев у нас не было в предыдущих заданиях, так что в репозиторий данный код (и все что относится к модели) запушен впервые

2020-09-22 07:54 UTC, IvanShamatov approved these changes
Найс, отличная работа. Пожалуйста, поправь текущие замечания перед мерджем.
Что же касается вопроса с токеном, то его обычно берут из метатегов и подставляют либо хидден полем, либо перехватывают запрос, и пишут свою отправку формы, подставляя токен.
Токен же получают так:
`var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');`

2020-09-22 07:54 UTC, IvanShamatov commented on app/controllers/concerns/rated.rb
> +    before_action :set_rateable, only: %i[rate_up, rate_down, cancel_vote]
эта штука не работает. в таком списке не нужны запятые
```ruby
2.6.3 :003 > %i[rate_up, rate_down, cancel_vote]
 => [:"rate_up,", :"rate_down,", :cancel_vote]
2.6.3 :004 > %i[rate_up rate_down cancel_vote]
 => [:rate_up, :rate_down, :cancel_vote]
```
Разница критическая. Вопрос, как прошли спеки?

2020-09-22 07:54 UTC, IvanShamatov commented on app/controllers/concerns/rated.rb
>        @rateable.rate_up(current_user)
я к сожалению не могу оставить коммент к коду ниже, 
Rated и Commented очень похожи по смыслу, может быть получение `@rateable` сделать по той же схеме, как ты получаешь record, без дополнительного вызова из базы?

2020-09-22 07:54 UTC, IvanShamatov commented on app/javascript/channels/answers_channel.js
> +            const template = require('./handlebars/answer.hbs')
handlebars -- отличный шаблонизатор, только папку можно было бы назвать templates, ведь ты же папки с вьюхами не называешь slim, или erb

2020-09-30 11:44 UTC, merged